### PR TITLE
[v4.0.0.1-jwst] DB connect with retry on failure

### PR DESCRIPTION
**Pull request by dchitti-stsci**
Same changes in https://github.com/spacetelescope/pandokia/pull/88 for v4.0.01-jwst

### CODE REVIEW

**Review by cdsontag — COMMENTED** [review]
If I read this right, the **max** this delays for a connection that is fully borked is only 0.15 sec (3 X 0.05) ?   Is that long enough to handle the outages we had been seeing?  Wondering if the sleep time should be a bit longer

**Comment by cdsontag** [comment]
I was just asking about timing.  Is 0.15s long enough to wait till the error goes away?  You said "From Kibana logs I have observed that there are some successful SQL transactions around the same time as the error." - does that mean you think the connection window is very small?

**Comment by dchitti-stsci** [comment]
> long enough to wait till the connection-problem goes away

The problem is because the RDS endpoint is not resolved due to some dropped packets in amazon route 53 (domain name system) and the dropping of packets is random and does not happen over a period of time. And resolving the RDS endpoint ideally should not take more than a few milliseconds.

Just checked with Tanner about the time between retries and he says that should be good, and the no. of retries matter (so that the re-query of the RDS endpoint resolution happens) than increasing the time between retries.

On a side note, just increase the time between retries, the overall db connection takes longer and pandeia would log it as SLOW QUERY.

**Comment by cdsontag** [comment]
You answered my question when you said "resolving the RDS endpoint ideally should not take more than a few milliseconds".  I wasn't advocating for more sleep vs more retries or vice versa.

**Comment by dchitti-stsci** [comment]
> You answered my question when you said "resolving the RDS endpoint ideally should not take more than a few milliseconds". I wasn't advocating for more sleep vs more retries or vice versa.

I think if we add more than 3 retries, we might end up masking some other db connection issues if and when it occurs.

**Comment by cdsontag** [comment]
> I think if we add more than 3 retries, we might end up masking some other db connection issues if and when it occurs.

Agreed, since that totals 0.15s.   Agreed we don't want extra delays or to mask other db connection issues

**Comment by cdsontag** [comment]
I'm not sure what v4.0.01-jwst is, so I'll wait to okay this until the convo happens

**Review by oiintam — APPROVED** [review]

**Pull request merged**
