### PR TITLE
For test page output, use flex_decode() func to guess at correct string encoding to use

### PR DESCRIPTION
**Pull request by cdsontag**
For test page output, use flex_decode() func to guess at correct string encoding to use.

When posting strings from a web page, I think it is safe to say we cannot always know the encoding being used, though 95% of the time it is utf-8.

### CODE REVIEW

**Comment by cdsontag** [comment]
Before pic:

image

and the bottom half with the actual error:

image

**Comment by cdsontag** [comment]
This is an after-pic, showing the *mu* at the very end of the output:

image

**Review by dchitti-stsci — APPROVED** [review]

**Review by ibusko — APPROVED** [review]
LGTM

**Comment by cdsontag** [comment]
Going to merge since this has 2 green checks and has been demo'd already in pdk "ops".

CC @vglaidler  for info though you have asked not to be tagged on PRs

**Comment by vglaidler** [comment]
Thanks @cdsontag , I did see this PR & I think I'd like to make an exception for any Pandokia changes that might occur going forward (ie,  pls do  tag me on Pandokia  PRs).

**Pull request merged**
